### ISSUE TITLE
Look into geojson-equality

### ISSUE THREAD

**Issue by tchannel** [Turfjs/turf-equal#2]
https://github.com/geosquare/geojson-equality

handles winding as well as #1. Performance seems good on a very simple case:

turf-equals x 31,380 ops/sec ±0.28% (102 runs sampled)
geojson-equality x 93,081 ops/sec ±0.24% (99 runs sampled)

using the same polygon pair I mentioned in #1. It looks like it doesn't use the optimization of simply checking object equality first, and by default will compare *properties* on features as well as geometry.

**Comment by tmcw** [comment]
Looks interesting, on a quick glance there are a few improvements we'd need to make:

* doesn't recurse on feature properties
* doesn't compare coordinates beyond x and y

**Comment by tchannel** [comment]
on the plus side, looks like it's still active, so we could request some pulls for those features upstream

**Comment by tchannel** [comment]
deep equality: [pull-requested](https://github.com/geosquare/geojson-equality/pull/4)

I'll do a PR for 3d points later

**Comment by tchannel** [comment]
@tmcw both of points you mentioned have been merged: [here](https://github.com/geosquare/geojson-equality/pull/5) and [here](https://github.com/geosquare/geojson-equality/pull/4)

**Comment by tmcw** [comment]
:+1: let's switch
